### Get all products
GET localhost:8080/shop-rest/api/products

### Get single product by id
GET localhost:8080/shop-rest/api/products/1

### Get non-existing product by id
GET localhost:8080/shop-rest/api/products/3